package by.it_academy.practice.practice27.tryCatchExample;

public class Main {
    public static void main(String[] args) {
//        try {
//            System.out.println("Inside try-block");
//        } catch (Exception e) {
//        } catch (IOException e) {
//        }

//        try {
//            System.out.print("Inside empty try");
//        }
//        System.out.print("\n");
//        catch (Exception e) {
//        }

//        try {
//            System.out.println("Inside try-block");
//        } catch (IOException e) {
//        }

//        try {
//            System.out.println("Inside try-block");
//        } catch (Exception e) {
//        }

        }
    }
